title: In My Voice
description: Reference website for the app In My Voice
theme: just-the-docs

url: https://docs.whisper-project.github.io

plugins:
  - jekyll-relative-links

mermaid:
  version: 10.3

aux_links:
  "Whisper Project": 
    - "http://whisper-project.org"

aux_links_new_tab: true
